class PropertyName:
    CREDENTIAL_INFO_TYPE_REGIST = "REGIST"
    CREDENTIAL_INFO_TYPE_REVOKE = "REVOKE"
    CREDENTIAL_INFO_TYPE_COMMON = "COMMON"

    CREDENTIAL_INFO_ISSUER_DID = "issuerDid"
    CREDENTIAL_INFO_HOLDER_DID = "holderDid"
    CREDENTIAL_INFO_SIGNATURE = "sig"

    CREDENTIAL_INFO_ISSUE_DATE = "issueDate"
    CREDENTIAL_INFO_REVOKE_DATE = "revokeDate"
    CREDENTIAL_INFO_EXPIRY_DATE = "expiryDate"

    CREDENTIAL_INFO_REVOKE_STATUS = "is_revoke"
    CREDENTIAL_INFO_REVOKE_STATUS2 = "isRevoke"

    CREDENTIAL_INFO_CREATED = "created"
    CREDENTIAL_INFO_REVOKED = "revoked"

    REJECT_HISTORY_REPORTER_DID = "reporterDid"
    REJECT_HISTORY_VC_ID = "vcId"
    REJECT_HISTORY_REJECT_CODE = "rejectCode"
    REJECT_HISTORY_REJECT_MESSAGE = "rejectMessage"
    REJECT_HISTORY_REPORTER_NAME = "reporterName"
    REJECT_HISTORY_TX_HASH = "txHash"

    REJECT_HISTORY_COUNT = "count"
    REJECT_HISTORY_HISTORY = "history"
