name: CI

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Change private repo url
        run: |
          sed -i -e "s/git@/${{ secrets.ICONLOOP_PRIVATE_REPO_ACCESS_TOKEN }}@/" -e "s/git+ssh:/git+https:/" requirements.txt
      - name: Install dependencies for ecdsa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgmp3-dev \
          libmpfr-dev \
          libmpc-dev
      - name: Install dependencies
        run: |
          python -V
          pip install -e .[tests]
      - name: Run unit tests
        run: pytest -vx
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Remove unnecessary dependencies for lint test
        run: |
          echo "" > requirements.txt
      - name: Install dependencies
        run: |
          python -V
          pip install -e .[lint]
      - name: Lint
        run: flake8
