name: Unittest

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Change private repo url
        run: |
          sed -i -e "s/git@/${{ secrets.ICONLOOP_PRIVATE_REPO_ACCESS_TOKEN }}@/" -e "s/git+ssh:/git+https:/" pyproject.toml
      - name: Install dependencies for ecdsa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgmp3-dev \
          libmpfr-dev \
          libmpc-dev
      - name: Install dependencies
        run: |
          python -V
          pip install -e .[dev]
      - name: Run unit tests
        run: pytest -vx